name: Build and Deploy Dockerized Node.js Service

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/dockerized-node-service:latest .

      - name: Push Docker image
        run: |
          docker push \
            ghcr.io/${{ github.repository_owner }}/dockerized-node-service:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/dockerized-node-service:latest

            docker stop node-service || true
            docker rm node-service || true

            docker run -d \
              --name node-service \
              -p 3000:3000 \
              -e USERNAME="${{ secrets.APP_USERNAME }}" \
              -e PASSWORD="${{ secrets.APP_PASSWORD }}" \
              -e SECRET_MESSAGE="${{ secrets.SECRET_MESSAGE }}" \
              ghcr.io/${{ github.repository_owner }}/dockerized-node-service:latest
